# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.12
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: huzaifatg2000@gmail.com
author_name: huzaifatg
cloud_provider: none
preset_name: production
project_name: Patentize-frontend

